# Generated by Django 4.0.4 on 2024-02-09 18:58

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='CA'),
        ),
    ]
